# Redirect to wedding website
[[redirects]]
  from = "/w"
  to = "https://stevenandcassidy.com/"
  status = 302
  force = true
  
[[redirects]]
  from = "/c"
  to = "https://sites.google.com/view/cassidy-okenica"
  status = 302
  force = true

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'none'; script-src 'self'; connect-src 'self'; img-src 'self'; style-src 'self'; font-src 'self'; form-action 'self';"

    # Multi-key header rules are expressed with multi-line strings.
    Link = '''
    </css/app.css>; rel=preload; as=style, \
    </app.js>; rel=preload; as=script, \
    </pics/me.jpg>; rel=preload; as=image'''
